---
- name: ec2
  hosts: localhost
  gather_facts: False
  connection: local

  vars:
    vault_aws_access_key: AKIAXV7G7FZVS5FFCVSA
    vault_aws_secret_key: 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

  tasks:
  - name: launch ec2
    ec2:
      aws_access_key: '{{ vault_aws_access_key }}'
      aws_secret_key: '{{ vault_aws_secret_key }}'
      instance_type: t2.micro
      keypair: controller_kp
      image: ami-005bdb005fb00e791 
      region: us-west-2
      group: controller_sg
      count: 1
      vpc_subnet_id: subnet-53143625
      wait: yes
      assign_public_ip: yes 
      user_data: "{{ lookup('file', 'user_data.sh') }}"
