---
- name: ec2
  hosts: localhost
  gather_facts: False
  connection: local
  
  vars:
    instance_ids:
      - 'i-08ea933a091782da6'
      - 'i-0640fab7bd1ba15ff'
    region: us-west-2

  tasks:
  - name: stop ec2
    ec2:
      aws_access_key: '{{ vault_aws_access_key }}'
      aws_secret_key: '{{ vault_aws_secret_key }}'
      instance_ids: '{{ instance_ids }}' 
      key_name: controller_kp
      region: '{{ region }}'
      state: stopped
      vpc_subnet_id: subnet-53143625
      wait: yes
