---
- name: ec2
  hosts: localhost
  gather_facts: False
  connection: local
  
  vars:
    instance_ids:
      - 'i-0b09960931c86e554'
    region: us-east-1

  tasks:
  - name: stop ec2
    ec2:
      aws_access_key: '{{ vault_aws_access_key }}'
      aws_secret_key: '{{ vault_aws_secret_key }}'
      instance_ids: '{{ instance_ids }}' 
      #keypair: myzone
      key_name: myzone
      region: '{{ region }}'
      state: stopped
      vpc_subnet_id: subnet-8cf889eb
      wait: yes
