---

- name: include ec2 key variable file
  include_vars:
    file: ./../../../group_vars/all.yml

- name: include ec2 variable file
  include_vars:
    file: ./../../../group_vars/main.yml

  vars:
    instance_ids:
      - 'i-08ea933a091782da6'
      - 'i-0640fab7bd1ba15ff'
    region: '{{ vault_region }}' 

  tasks:
  - name: stop ec2
    ec2:
      aws_access_key: '{{ vault_aws_access_key }}'
      aws_secret_key: '{{ vault_aws_secret_key }}'
      instance_ids: '{{ instance_ids }}' 
      key_name: '{{ vault_key_name }}'
      region: '{{ region }}'
      state: stopped
      vpc_subnet_id: '{{ vault_vpc_subnet_id }}'
      wait: yes
