---
- name: Download Splunk Enterprise
  get_url: 
    url: https://www.splunk.com/bin/splunk/DownloadActivityServlet?architecture=x86_64&platform=linux&version=7.2.4.2&product=splunk&filename=splunk-7.2.4.2-fb30470262e3-linux-2.6-x86_64.rpm&wget=true
    dest: /tmp/splunk-7.2.4.2-fb30470262e3-linux-2.6-x86_64.rpm
