---
vault_aws_access_key: AKIAXV7G7FZVS5FFCVSA
vault_aws_secret_key: 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
instance_type: t2.micro
keypair: controller_kp
image: ami-005bdb005fb00e791
region: us-west-2
